services:
  api:
    build:
      context: .
    container_name: insurance-rag-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app  # 개발 편의: 소스 실시간 반영
    command: >
      uvicorn app.main:app
      --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app