legal:
  disclaimer: >
    본 답변은 참고용 정보이며, 실제 보상/보장 여부 및 한도는
    보험증권과 해당 상품의 최신 약관에 따릅니다. 정확한 확인을 위해
    반드시 보험사 공식 문서 및 고객센터로 재확인하시기 바랍니다.

web:
  source_whitelist:
    - mofa.go.kr
    - cdc.gov
    - who.int
    - faa.gov
    - fsc.go.kr

answer:
  min_citations: 1
  min_context: 1

# 의도별 요구사항 설정
intent_requirements:
  qa:
    min_context: 1
    min_citations: 1
    min_insurers: 1
  compare:
    min_context: 3
    min_citations: 3
    min_insurers: 2
  summary:
    min_context: 2
    min_citations: 2
    min_insurers: 1
  recommend:
    min_context: 3
    min_citations: 3
    min_insurers: 2

# 품질 기준 설정
quality:
  min_score: 0.3          # 최소 스코어 임계치
  max_age_days: 365      # 최대 문서 나이 (일)
  
# 출처 신뢰도 가중치
source_weights:
  공식약관: 1.0
  공지: 0.9
  안내: 0.8
  기타: 0.7

# 시스템 전역 설정
system:
  # 재검색 관련 설정
  replan:
    max_attempts: 3                    # 최대 재검색 시도 횟수
    max_structured_failures: 2         # 최대 연속 구조화 실패 허용 횟수
    quality_threshold: 0.7             # 품질 평가 임계값
    emergency_fallback_threshold: 3     # 긴급 탈출 임계값 (재검색 횟수)
  
  # 성능 최적화 설정
  performance:
    enable_llm_classification: true     # LLM 분류 사용 여부
    fallback_priority: true            # fallback 분류 우선 사용
    complex_case_threshold: 2          # 복잡한 케이스 판단 임계값